[project]
name = "computing-timeline"
version = "0.1.0"
description = "Timeline of computing history"
authors = [
    { name = "Khaled Hammouda" }
]
requires-python = ">=3.13"
dependencies = [
    "django~=5.2.4",
    "django-mass-edit>=3.5.0",
]
