# Generated by Django 4.1.5 on 2023-01-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
