# Generated by Django 4.0.4 on 2023-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_topic_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='abbr',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
