# Generated by Django 4.1.5 on 2023-02-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_entry_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='weight',
            field=models.IntegerField(choices=[(-1, '-1'), (0, '0'), (1, '+1')], default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('T', 'Topic'), ('C', 'Computer / Computer Family'), ('O', 'Organization'), ('P', 'Person')], default='T', max_length=2),
        ),
    ]
